Fix patterns for Django > 1.10
Pike requires Django 1.11 so fix the template pattern import which was
not compatible with that version. This fixes:

File
"/srv/www/openstack-dashboard/openstack_dashboard/dashboards/help/guides/\
    urls.py", line 15, in <module>
from django.conf.urls import patterns, url
ImportError: cannot import name patterns